version: 0.0
os: linux
files:
  - source: /radio-frontend.tgz
    destination: /opt/claqradio/radio-frontend/
permissions:
  - object: /opt/claqradio/radio-frontend
    pattern: "**"
    owner: ubuntu
    group: ubuntu
hooks:
  AfterInstall:
    - location: scripts/deploy_setup.rb
      runas: ubuntu

